### ISSUE TITLE
No module named grabcut

### ISSUE THREAD

**Issue by hellocatfood** [sleeepyy/GrabCut-UI#1]
I tried running this script and got the following error.
```
[INFO   ] [Logger      ] Record log in /home/hellocatfood/.kivy/logs/kivy_19-03-17_3.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "main.py", line 11, in <module>
     import grabcut
 ImportError: No module named grabcut
```

I can't find a module named grabcut in pip or Ubuntu repositories

**Comment by yang-han** [comment]
Sorry for the inconvenience caused. 
Actually, this is just a demo kivy frontend code for grabcut. So the grabcut model needs to be implemented by yourself and import to this code. 
By the way, I will not recommend you to use this code in any case. The codes can be seen as a practice of writing simple UI. So forget about this repo.  

And OpenCV has already provided a grabcut implementation of grabcut with UI. You may refer to that and run it instead of this repo.

Sorry again.
